### ISSUE TITLE
Unhandled IO error when trying to use existing db files

### ISSUE THREAD

**Issue by drschwabe** [hoodiehq/spawn-pouchdb-server#22]
Trying to create an app that will attempt to spawn a server but if server already exists and/or is running the logic to accommodate that would be handled in spawnPouchdbServer's callback. 

However, seems there is an unhandled error along the way that is preventing the callback function from returning.   

```
Error: Port 3000 is already in use.
Try another one, e.g. pouchdb-server -p 3001
Unhandled rejection OpenError: IO error: lock /home/derrick/myapp/pouch/_replicator/LOCK: Resource temporarily unavailable
    at /home/derrick/myapp/node_modules/spawn-pouchdb-server/node_modules/pouchdb-server/node_modules/pouchdb/node_modules/levelup/lib/levelup.js:119:34
    at /home/derrick/myapp/node_modules/spawn-pouchdb-server/node_modules/pouchdb-server/node_modules/pouchdb/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

The spawn attempt looks like: 

```
spawnPouchdbServer({
    port: 3000,
    directory:'my_path', 
    config: {
      file: 'my_path/config.json'
    }
  }, function (error, server) {
  console.log("Did I get called?")
  //not getting called if server already running :(
}
```

The uhnandled error seems to occur when db files are already in use - but this should be handled gracefully and the details passed along to the error object.

**Comment by gr2m** [comment]
I agree. The code is pretty simple, want to find the fix for that and send a PR? I’m heads down on something else right now

**Comment by drschwabe** [comment]
Sure I can take a look next time I have a chance to work on this app again.

**Comment by drschwabe** [comment]
Seems that in order to catch errors effectively the server object returned by the initial spawnPouchdbServer should support promises.   Ie: 

```
spawnPouchdbServer(function (error, server) {
  console.log('PouchDB Server stared at localhost:5985/_utils')
  server.on('error', function(pouchServerError) { 
     console.log(pouchServerError)
  })
})
```

From what I can tell, this may also require an update to [pouchdb-server](https://github.com/pouchdb/pouchdb-server) to emit events in such a way that can we can listen to.

**Comment by gr2m** [comment]
please not that I can no longer maintain this module, but am happy to give committer rights or hand it over entirely if you are interested. If you no longer use it, please close the issue :)

**Comment by drschwabe** [comment]
Thanks for the offer, yes I do still use spawn-pouchdb-server - it's a brilliant idea and so handy for quickly deploying Pouch/Couch apps on servers without needing to setup a whole CouchDB install.  

However I'm probably not the best option for a maintainer moving forward - maybe @nolanlawson ,  @garrensmith , or someone else on the Pouch crew would be interested.  

Perhaps even the entire functionality of this module could be merged into pouchdb-server itself ?

**Comment by nolanlawson** [comment]
I am not really much involved in pouchdb-server/express-pouchdb anymore TBH...

**Comment by gr2m** [comment]
@cdaringe mentioned that he’d be interested in helping to maintain it. I think the PouchDB core people are busy with PouchDB itself, ideally someone who is actually using spawn-pouchdb-server in a production environment would be the best

**Comment by cdaringe** [comment]
I'll look at this probably next week
